var list_entities_1 = [
{ y: 69092, label: "Virgin Islands"},
{ y: 51295, label: "Hong Kong"},
{ y: 38077, label: "Switzerland"},
{ y: 18122, label: "Panama"},
{ y: 17973, label: "United Kingdom"},
{ y: 14562, label: "Jersey"},
{ y: 11516, label: "Russian Federation"},
{ y: 10877, label: "Luxembourg"},
{ y: 9729, label: "Samoa"},
{ y: 7772, label: "United Arab Emirates"},
];
var list_entities_2 = [
{ y: 101863, label: "Virgin Islands"},
{ y: 75005, label: "Hong Kong"},
{ y: 38112, label: "Switzerland"},
{ y: 18036, label: "Panama"},
{ y: 21165, label: "United Kingdom"},
{ y: 41536, label: "Jersey"},
{ y: 13125, label: "Russian Federation"},
{ y: 12733, label: "Luxembourg"},
{ y: 17518, label: "Samoa"},
{ y: 8591, label: "United Arab Emirates"},
];
var list_entities_3 = [
{ y: 29976, label: "Virgin Islands"},
{ y: 81779, label: "Hong Kong"},
{ y: 9101, label: "Switzerland"},
{ y: 16243, label: "Panama"},
{ y: 49761, label: "United Kingdom"},
{ y: 6064, label: "Jersey"},
{ y: 15100, label: "Russian Federation"},
{ y: 5421, label: "Luxembourg"},
{ y: 9259, label: "Samoa"},
{ y: 10491, label: "United Arab Emirates"},
];
var donut_entities = [
{ y: 69092, indexLabel: "Virgin Islands"},
{ y: 51295, indexLabel: "Hong Kong"},
{ y: 38077, indexLabel: "Switzerland"},
{ y: 18122, indexLabel: "Panama"},
{ y: 17973, indexLabel: "United Kingdom"},
{ y: 14562, indexLabel: "Jersey"},
{ y: 11516, indexLabel: "Russian Federation"},
{ y: 10877, indexLabel: "Luxembourg"},
{ y: 9729, indexLabel: "Samoa"},
{ y: 7772, indexLabel: "United Arab Emirates"},
];
var list_interIn_1 = [
{ y: 69092, label: "Virgin Islands"},
{ y: 51295, label: "Hong Kong"},
{ y: 14562, label: "Jersey"},
{ y: 38077, label: "Switzerland"},
{ y: 7332, label: "Guernsey"},
{ y: 17973, label: "United Kingdom"},
{ y: 18122, label: "Panama"},
{ y: 9729, label: "Samoa"},
{ y: 4188, label: "China"},
{ y: 5869, label: "Singapore"},
];
var list_interIn_2 = [
{ y: 101863, label: "Virgin Islands"},
{ y: 75005, label: "Hong Kong"},
{ y: 41536, label: "Jersey"},
{ y: 38112, label: "Switzerland"},
{ y: 26493, label: "Guernsey"},
{ y: 21165, label: "United Kingdom"},
{ y: 18036, label: "Panama"},
{ y: 17518, label: "Samoa"},
{ y: 15543, label: "China"},
{ y: 13251, label: "Singapore"},
];
var list_interIn_3 = [
{ y: 29976, label: "Virgin Islands"},
{ y: 81779, label: "Hong Kong"},
{ y: 6064, label: "Jersey"},
{ y: 9101, label: "Switzerland"},
{ y: 5212, label: "Guernsey"},
{ y: 49761, label: "United Kingdom"},
{ y: 16243, label: "Panama"},
{ y: 9259, label: "Samoa"},
{ y: 54944, label: "China"},
{ y: 115099, label: "Singapore"},
];
var donut_interIn = [
{ y: 101863, indexLabel: "Virgin Islands"},
{ y: 75005, indexLabel: "Hong Kong"},
{ y: 41536, indexLabel: "Jersey"},
{ y: 38112, indexLabel: "Switzerland"},
{ y: 26493, indexLabel: "Guernsey"},
{ y: 21165, indexLabel: "United Kingdom"},
{ y: 18036, indexLabel: "Panama"},
{ y: 17518, indexLabel: "Samoa"},
{ y: 15543, indexLabel: "China"},
{ y: 13251, indexLabel: "Singapore"},
];
var list_interOff_1 = [
{ y: 5021, label: "Bahamas"},
{ y: 5869, label: "Singapore"},
{ y: 71, label: "Indonesia"},
{ y: 1013, label: "Thailand"},
{ y: 51295, label: "Hong Kong"},
{ y: 2906, label: "Taiwan"},
{ y: 4188, label: "China"},
{ y: 17973, label: "United Kingdom"},
{ y: 69092, label: "Virgin Islands"},
{ y: 6254, label: "United States of America"},
];
var list_interOff_2 = [
{ y: 4873, label: "Bahamas"},
{ y: 13251, label: "Singapore"},
{ y: 924, label: "Indonesia"},
{ y: 1681, label: "Thailand"},
{ y: 75005, label: "Hong Kong"},
{ y: 6994, label: "Taiwan"},
{ y: 15543, label: "China"},
{ y: 21165, label: "United Kingdom"},
{ y: 101863, label: "Virgin Islands"},
{ y: 7310, label: "United States of America"},
];
var list_interOff_3 = [
{ y: 180056, label: "Bahamas"},
{ y: 115099, label: "Singapore"},
{ y: 99442, label: "Indonesia"},
{ y: 83105, label: "Thailand"},
{ y: 81779, label: "Hong Kong"},
{ y: 61241, label: "Taiwan"},
{ y: 54944, label: "China"},
{ y: 49761, label: "United Kingdom"},
{ y: 29976, label: "Virgin Islands"},
{ y: 20589, label: "United States of America"},
];
var donut_interOff = [
{ y: 180056, indexLabel: "Bahamas"},
{ y: 115099, indexLabel: "Singapore"},
{ y: 99442, indexLabel: "Indonesia"},
{ y: 83105, indexLabel: "Thailand"},
{ y: 81779, indexLabel: "Hong Kong"},
{ y: 61241, indexLabel: "Taiwan"},
{ y: 54944, indexLabel: "China"},
{ y: 49761, indexLabel: "United Kingdom"},
{ y: 29976, indexLabel: "Virgin Islands"},
{ y: 20589, indexLabel: "United States of America"},
];
var country_select = {
AGO: "Angola",
LIE: "Liechtenstein",
EGY: "Egypt",
BGD: "Bangladesh",
QAT: "Qatar",
NAM: "Namibia",
BGR: "Bulgaria",
BOL: "Bolivia",
GHA: "Ghana",
PAK: "Pakistan",
PAN: "Panama",
JOR: "Jordan",
LBR: "Liberia",
LBY: "Libya",
MYS: "Malaysia",
PRI: "Puerto Rico",
SXM: "Sint Maarten (Dutch part)",
TZA: "Tanzania",
PRT: "Portugal",
KHM: "Cambodia",
PRY: "Paraguay",
HKG: "Hong Kong",
SAU: "Saudi Arabia",
LBN: "Lebanon",
SVN: "Slovenia",
BFA: "Burkina Faso",
CHE: "Switzerland",
HRV: "Croatia",
CHL: "Chile",
CHN: "China",
KNA: "Saint Kitts and Nevis",
JAM: "Jamaica",
GIB: "Gibraltar",
DJI: "Djibouti",
GIN: "Guinea",
FIN: "Finland",
URY: "Uruguay",
THA: "Thailand",
SYC: "Seychelles",
NPL: "Nepal",
MAR: "Morocco",
YEM: "Yemen",
PHL: "Philippines",
ZAF: "South Africa",
NIC: "Nicaragua",
MNE: "Montenegro",
VIR: "Virgin Islands",
SYR: "Syrian Arab Republic",
MAC: "Macao",
MAF: "Saint Martin (French part)",
MLT: "Malta",
KAZ: "Kazakhstan",
COK: "Cook Islands",
TCA: "Turks and Caicos Islands",
PYF: "French Polynesia",
NIU: "Niue",
DMA: "Dominica",
BEN: "Benin",
NGA: "Nigeria",
BEL: "Belgium",
None: "None",
GUM: "Guam",
LKA: "Sri Lanka",
GBR: "United Kingdom",
MWI: "Malawi",
CRI: "Costa Rica",
CMR: "Cameroon",
MNP: "Northern Mariana Islands",
LSO: "Lesotho",
HUN: "Hungary",
TKM: "Turkmenistan",
TTO: "Trinidad and Tobago",
CPV: "Cabo Verde",
BMU: "Bermuda",
TCD: "Chad",
GEO: "Georgia",
ROU: "Romania",
MNG: "Mongolia",
MHL: "Marshall Islands",
MLI: "Mali",
BLZ: "Belize",
MMR: "Myanmar",
NFK: "Norfolk Island",
VGB: "Virgin Islands",
BLR: "Belarus",
GRD: "Grenada",
GRC: "Greece",
AND: "Andorra",
MOZ: "Mozambique",
TJK: "Tajikistan",
HTI: "Haiti",
PSE: "Palestine",
ZWE: "Zimbabwe",
LCA: "Saint Lucia",
IND: "India",
VCT: "Saint Vincent and the Grenadines",
BTN: "Bhutan",
VNM: "Viet Nam",
NOR: "Norway",
CZE: "Czechia",
ATG: "Antigua and Barbuda",
FJI: "Fiji",
HND: "Honduras",
MUS: "Mauritius",
DOM: "Dominican Republic",
LUX: "Luxembourg",
ISR: "Israel",
SMR: "San Marino",
PER: "Peru",
REU: "Réunion",
IDN: "Indonesia",
VUT: "Vanuatu",
MKD: "Macedonia",
SUR: "Suriname",
ISL: "Iceland",
GAB: "Gabon",
ETH: "Ethiopia",
NER: "Niger",
COL: "Colombia",
BWA: "Botswana",
NRU: "Nauru",
MDA: "Moldova",
GGY: "Guernsey",
MDG: "Madagascar",
ECU: "Ecuador",
SEN: "Senegal",
MDV: "Maldives",
ASM: "American Samoa",
CUW: "Curaçao",
FRA: "France",
LTU: "Lithuania",
RWA: "Rwanda",
ZMB: "Zambia",
TWN: "Taiwan",
JEY: "Jersey",
IRL: "Ireland",
GTM: "Guatemala",
DNK: "Denmark",
DEU: "Germany",
NLD: "Netherlands",
AUS: "Australia",
AUT: "Austria",
VEN: "Venezuela",
KEN: "Kenya",
LAO: "Lao People's Democratic Republic",
WSM: "Samoa",
TUR: "Turkey",
JPN: "Japan",
ALB: "Albania",
OMN: "Oman",
ITA: "Italy",
BRN: "Brunei Darussalam",
TUN: "Tunisia",
RUS: "Russian Federation",
MEX: "Mexico",
BRA: "Brazil",
CAN: "Canada",
SRB: "Serbia",
GNQ: "Equatorial Guinea",
USA: "United States of America",
SWE: "Sweden",
AZE: "Azerbaijan",
GNB: "Guinea-Bissau",
SWZ: "Swaziland",
TON: "Tonga",
CIV: "Côte d'Ivoire",
UKR: "Ukraine",
KOR: "Korea",
AIA: "Anguilla",
GUY: "Guyana",
SVK: "Slovakia",
CYP: "Cyprus",
DZA: "Algeria",
SGP: "Singapore",
XXX: "XXX",
SOM: "Somalia",
UZB: "Uzbekistan",
CAF: "Central African Republic",
POL: "Poland",
KWT: "Kuwait",
GMB: "Gambia",
TGO: "Togo",
CYM: "Cayman Islands",
EST: "Estonia",
ESP: "Spain",
IRQ: "Iraq",
SLV: "El Salvador",
MTQ: "Martinique",
LVA: "Latvia",
IRN: "Iran",
ABW: "Aruba",
SLE: "Sierra Leone",
IMN: "Isle of Man",
BHS: "Bahamas",
SLB: "Solomon Islands",
NZL: "New Zealand",
MCO: "Monaco",
COD: "Congo",
BIH: "Bosnia and Herzegovina",
BRB: "Barbados",
KGZ: "Kyrgyzstan",
UGA: "Uganda",
ARE: "United Arab Emirates",
ARG: "Argentina",
SDN: "Sudan",
BHR: "Bahrain",
ARM: "Armenia",
PNG: "Papua New Guinea",
CUB: "Cuba",
};
